# Nombre de pipeline
name: Integracion continua

# Los pasos a ejecutar
jobs:
  build-test:
    run-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Ejecutar las pruebas
        run: ./gradlew test --no-daemon

# Ejecutar el pipeline cada push sobre la rama master
on:
  push:
    branches:
      - main
